repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      # - id: no-commit-to-branch
      #   args: ["--branch", "main"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.7
    hooks:
      - id: ruff
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.4
    hooks:
      - id: uv-lock
      - id: uv-export
        args: ["--no-annotate", "--format", "requirements-txt", "-o", "requirements.txt"]
